### ISSUE TITLE
In the play book mezzanine.yml ,where are the variable {{python}} and {{ansible_ssh_user}} defined?

### ISSUE THREAD

**Issue by jybertrand** [lorin/ansiblebook#13]

**Comment by lorin** [comment]
`python` is defined in [the vars section](https://github.com/ansiblebook/ansiblebook/blob/b760728f52cf87ec41e2e740becf723a708bd1bd/ch06/playbooks/mezzanine.yml#L24).

`ansible_ssh_user` is an Ansible built-in variable.
